var NumberOfWords = 100

var words = new BuildArray(NumberOfWords)

// Use the following variables to
// define your random words:
words[1] = "서대문형무소역사관"
words[2] = "서울 5대 고궁"
words[3] = "서울 N서울타워"
words[4] = "익선동"
words[5] = "서울시립미술관"
words[6] = "동대문디자인플라자"
words[7] = "홍대거리"
words[8] = "코엑스"
words[9] = "롯데월드"
words[10] = "임진각과 파주 DMZ"
words[11] = "강화 원도심 스토리워크"
words[12] = "파주 헤이리예술마을"
words[13] = "개항장문화지구"
words[14] = "가평 아침고요수목원"
words[15] = "영종도"
words[16] = "송도 센트럴파크"
words[17] = "광명동굴"
words[18] = "두물머리"
words[19] = "화담숲"
words[20] = "소래포구"
words[21] = "서울대공원"
words[22] = "에버랜드"
words[23] = "제부도"
words[24] = "수원화성"
words[25] = "한국민속촌"
words[26] = "안성팜랜드"
words[27] = "한탄강 유네스코 세계지질공원"
words[28] = "설악산 국립공원"
words[29] = "원대리 자작나무숲"
words[30] = "남이섬"
words[31] = "비발디파크"
words[32] = "대관령"
words[33] = "주문진"
words[34] = "뮤지엄 산"
words[35] = "강릉커피거리"
words[36] = "간현관광지"
words[37] = "산두리해안사구"
words[38] = "공주 백제유적지"
words[39] = "아산 외암마을"
words[40] = "안면도 꽃지해변"
words[41] = "예당호출렁다리"
words[42] = "예산황새공원"
words[43] = "대천 해수욕장"
words[44] = "부여 백제 유적지"
words[45] = "세종호수공원 일원"
words[46] = "청남대"
words[47] = "계족산 황톳길"
words[48] = "정태산 자연휴양림"
words[49] = "청풍호 케이블카"
words[50] = "의림지"
words[51] = "민천하스카이워크"
words[52] = "부석사"
words[53] = "안동하회마을"
words[54] = "병산서원"
words[55] = "팔공산"
words[56] = "수성못"
words[57] = "서문시장"
words[58] = "경주 대릉원"
words[59] = "불국사&석굴암"
words[60] = "영남알프스"
words[61] = "합천 해인사"
words[62] = "태화강 국가정원"
words[63] = "반구대 암각화"
words[64] = "대왕암 공원"
words[65] = "간절곶"
words[66] = "황매산군립공원"
words[67] = "창녕 우포늪"
words[68] = "감천문화마을"
words[69] = "송정해수욕장"
words[70] = "해운대해수욕장"
words[71] = "태종대유원지"
words[72] = "환여울문화마을"
words[73] = "용궁구름다리&송도해수욕장"
words[74] = "용두산,자갈치 관광특구"
words[75] = "다대포해수욕장"
words[76] = "거제 바람의 언덕"
words[77] = "남해 독일마을"
words[78] = "동대문디자인플라자"
words[79] = "홍대거리"
words[80] = "익산 미륵사지"
words[81] = "전주 한옥마을"
words[82] = "마이산도립공원"
words[83] = "내장산국립공원"
words[84] = "옥정호 구절초 지방공원"
words[85] = "남원시립김병종미술관"
words[86] = "죽녹원"
words[87] = "국립아시아문화전당"
words[88] = "무등산국립공원"
words[89] = "순천만습지"
words[90] = "목포해상케이블카"
words[91] = "보성 녹차밭"
words[92] = "오동도&여수세계박람회장"
words[93] = "퍼플섬"
words[94] = "쑥섬"
words[95] = "제주 올레길"
words[96] = "한라산국립고원"
words[97] = "비자림"
words[98] = "성산일출봉"
words[99] = "카멜리아 힐"
words[100] = "우도"

function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}
